#!/bin/bash
cd /var/spool/mail
size=`wc -c lanh | awk '{print $1}'`
while true;
do
	newSize=`wc -c lanh | awk '{print $1}'`
	if [ $newSize -gt $size ]
	   then 
		echo "$USER, you have new mail"
		size=$newSize
	fi
	sleep 5 
done


